# Generated by doctest: do not edit by hand
# Please edit file in R/helpers.R

test_that("Doctest: rect_around", {
  # Created from @doctest for `rect_around`
  # Source file: R/helpers.R
  # Source line: 20
  library(ggplot2)
  to <- c(2, 4.5, 6, 8)
  setosas <- iris[iris$Species == "setosa", ]
  expect_silent(rect_around(Sepal.Width, Sepal.Length, data = setosas))
  expect_silent(hull_around(Sepal.Width, Sepal.Length, data = setosas))
})

