# Generated by doctest: do not edit by hand
# Please edit file in R/ggmagnify.R

test_that("Doctest: ggmagnify", {
  # Created from @doctest for `ggmagnify`
  # Source file: R/ggmagnify.R
  # Source line: 127
  library(ggplot2)
  expect_silent(ggp <- ggplot(ChickWeight, aes(Time, weight, group = Chick, color = Diet)) +
    geom_line())
  expect_silent(ggmagnify(ggp, xlim = c(0, 5), ylim = c(25, 75), inset_xlim = c(0, 10),
  inset_ylim = c(200, 400)))
  expect_silent(ggmagnify(ggp, xlim = c(0, 5), ylim = c(25, 75), inset_xlim = c(0, 10),
  inset_ylim = c(200, 400), axes = TRUE))
  if (requireNamespace("ggfx", quietly = TRUE)) {
    expect_silent(ggmagnify(ggp, xlim = c(0, 5), ylim = c(25, 75), inset_xlim = c(0,
      10), inset_ylim = c(200, 400), shadow = TRUE))
  }
})

