# Generated by doctest: do not edit by hand
# Please edit file in R/print.R

test_that("Doctest: compose", {
  # Created from @doctest for `compose`
  # Source file: R/print.R
  # Source line: 32
  library(ggplot2)
  ggp <- ggplot(ChickWeight, aes(Time, weight, group = Chick, color = Diet)) + geom_line()
  ggm <- ggmagnify(ggp, xlim = c(0, 5), ylim = c(30, 80), inset_xlim = c(0, 15),
  inset_ylim = c(200, 350))
  expect_silent(compose(ggm))
})

